<a href="https://colab.research.google.com/github/greenrobot8888/ds.tutorial3submission/blob/main/tutorialsubmmision3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.array([[1,2], [4,5]])

In [ ]:
print(array)

[[1 2]
 [4 5]]


In [ ]:
rdarray = np.random.randn(3,4)
print(rdarray)

[[ 0.05361805 -1.03986729  0.05360195 -0.1485352 ]
 [ 0.72273097  0.38585394  1.57875565 -0.15829995]
 [ 0.00757698 -2.08486348  0.23951593 -0.33250468]]


In [ ]:
onearray = np.ones([2,2])
zeroarray = np.zeros((2,2))
print(onearray)
print(zeroarray)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
A = np.random.randn(6,3)
print(A)
B = np.transpose(A)
print(B)

[[ 1.15007259 -0.01079853  1.96896705]
 [ 1.73822921 -0.42244965 -1.41264149]
 [ 0.50458331 -0.71942395 -0.71470796]
 [ 0.03954146  0.29752906  0.04279468]
 [ 0.49882599  0.37759887 -0.10523206]
 [-0.86905151 -0.68509201 -0.15191343]]
[[ 1.15007259  1.73822921  0.50458331  0.03954146  0.49882599 -0.86905151]
 [-0.01079853 -0.42244965 -0.71942395  0.29752906  0.37759887 -0.68509201]
 [ 1.96896705 -1.41264149 -0.71470796  0.04279468 -0.10523206 -0.15191343]]


In [ ]:
C = np.random.randn(2,3)
D = np.random.randn(3,4)
dot_product = np.dot(C,D)
print(C, D, dot_product)


[[ 0.9519651   0.15580503  0.49693798]
 [-0.47019655 -1.17674231 -1.82311644]] [[ 0.25992656  0.84353469  1.75034048  1.83550093]
 [ 0.9968538   0.66173195  2.02046958  0.89568923]
 [-0.65829383  1.60536542  1.01191013 -0.64751253]] [[ 0.07562464  1.70388379  2.48391894  1.56511214]
 [-0.09511031 -4.10208318 -5.0454061  -0.7365509 ]]
